// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7jadGkN7SQPCE6VOXl5WSDAppXal9qWE',
    appId: '1:1097341288012:web:8d328dfe50d285894e7ee9',
    messagingSenderId: '1097341288012',
    projectId: 'elt-app-7ca1b',
    authDomain: 'elt-app-7ca1b.firebaseapp.com',
    storageBucket: 'elt-app-7ca1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQxkzZaDxVhdPwLccRsMlaH9kfv10Ga9k',
    appId: '1:1097341288012:android:2ece9e82b3481b2a4e7ee9',
    messagingSenderId: '1097341288012',
    projectId: 'elt-app-7ca1b',
    storageBucket: 'elt-app-7ca1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwiNrOz8Dq6QUpxKrPUIT0L8NrU7JAdbA',
    appId: '1:1097341288012:ios:fa2fd36ff25d82b04e7ee9',
    messagingSenderId: '1097341288012',
    projectId: 'elt-app-7ca1b',
    storageBucket: 'elt-app-7ca1b.firebasestorage.app',
    iosClientId: '1097341288012-o1l91mvh68adbdav775np3fq68q2lhm1.apps.googleusercontent.com',
    iosBundleId: 'com.musicteam.musicTeamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7jadGkN7SQPCE6VOXl5WSDAppXal9qWE',
    appId: '1:1097341288012:web:8d328dfe50d285894e7ee9',
    messagingSenderId: '1097341288012',
    projectId: 'elt-app-7ca1b',
    authDomain: 'elt-app-7ca1b.firebaseapp.com',
    storageBucket: 'elt-app-7ca1b.firebasestorage.app',
  );

}